definitions:
  handlers.LoginInput:
    properties:
      identifier:
        description: 可以是 username 或 email
        type: string
      password:
        type: string
    required:
    - identifier
    - password
    type: object
  handlers.RegisterInput:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  models.Castle:
    properties:
      build_year:
        type: integer
      country:
        type: string
      description:
        type: string
      image_url:
        type: string
      name:
        type: string
      name_zh:
        type: string
      type:
        type: integer
    type: object
  models.CastleType:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      name_zh:
        type: string
    type: object
info:
  contact: {}
  description: Castle API for managing castles.
  title: Castle API
  version: "1.0"
paths:
  /castle-types:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CastleType'
            type: array
      summary: 取得所有城堡類型
      tags:
      - CastleType
  /castles:
    get:
      consumes:
      - application/json
      description: 取得城堡列表，支援分頁
      parameters:
      - default: 1
        description: 第幾頁
        in: query
        name: page
        type: integer
      - default: 10
        description: 每頁幾筆
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 取得城堡列表（分頁）
      tags:
      - 城堡
  /create-castle:
    post:
      consumes:
      - application/json
      description: 新增一筆城堡資料
      parameters:
      - description: 城堡資料
        in: body
        name: castle
        required: true
        schema:
          $ref: '#/definitions/models.Castle'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: 新增城堡
      tags:
      - 城堡
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登入資料
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 使用者登入
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 註冊資料
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 使用者註冊
      tags:
      - Auth
  /upload-castle-image:
    post:
      consumes:
      - multipart/form-data
      description: 上傳城堡圖片並儲存至 Cloudinary，返回圖片 URL
      parameters:
      - description: 城堡圖片
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: 上傳城堡圖片
      tags:
      - 圖片上傳
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
